class_name Employee
extends RefCounted
## One person on the payroll.
##
## Employees are simulated abstractly (they produce, sell, haul or guard at a
## property) and, when the player is nearby, an NPC body is spawned for them so
## the world reads as populated.

const ASSIGN_PRODUCTION := "production"
const ASSIGN_SELL := "sell"
const ASSIGN_SECURITY := "security"
const ASSIGN_HAUL := "haul"
const ASSIGN_IDLE := "idle"

const ASSIGN_LABELS := {
	ASSIGN_PRODUCTION: "Production",
	ASSIGN_SELL: "Street Sales",
	ASSIGN_SECURITY: "Security",
	ASSIGN_HAUL: "Supply Runs",
	ASSIGN_IDLE: "Unassigned",
}

var id: String = ""
var name: String = ""
var archetype: String = "hand"
var property_id: String = ""
var assignment: String = ASSIGN_IDLE
var wage: int = 45              ## per in-game day
var skill: float = 0.35         ## 0..1, affects quality and speed
var loyalty: float = 0.5        ## 0..1, drops when unpaid; low loyalty steals
var discretion: float = 0.4     ## 0..1, reduces heat generated by their work
var days_employed: int = 0
var unpaid_days: int = 0
var lifetime_produced: int = 0
var lifetime_sold: int = 0
var lifetime_earned: int = 0
var color: Color = Color(0.6, 0.7, 0.8)


static func create(archetype_id: String, person_name: String, unique_id: String) -> Employee:
	var e := Employee.new()
	var a: Dictionary = GameData.employee_archetypes.get(archetype_id, {})
	e.id = unique_id
	e.name = person_name
	e.archetype = archetype_id
	e.wage = int(a.get("wage", 45))
	e.skill = float(a.get("skill", 0.35))
	e.loyalty = float(a.get("loyalty", 0.5))
	e.discretion = float(a.get("discretion", 0.4))
	e.color = Color.from_hsv(randf(), 0.35, 0.85)
	return e


func label() -> String:
	return String(GameData.employee_archetypes.get(archetype, {}).get("label", "Worker"))


func can_do(job: String) -> bool:
	var jobs: Array = GameData.employee_archetypes.get(archetype, {}).get("jobs", [])
	return jobs.has(job)


## Effective output multiplier including the player's Foreman skill.
func effectiveness() -> float:
	var foreman: float = GameState.skill_effect("employee_output")
	return clampf((0.4 + skill * 0.9) * (0.55 + loyalty * 0.6) * (1.0 + foreman), 0.15, 3.0)


func daily_wage() -> int:
	var reduction: float = GameState.skill_effect("wage_reduction")
	return maxi(1, int(round(wage * (1.0 - clampf(reduction, 0.0, 0.6)))))


func to_dict() -> Dictionary:
	return {
		"id": id, "name": name, "archetype": archetype, "property_id": property_id,
		"assignment": assignment, "wage": wage, "skill": skill, "loyalty": loyalty,
		"discretion": discretion, "days_employed": days_employed,
		"unpaid_days": unpaid_days, "lifetime_produced": lifetime_produced,
		"lifetime_sold": lifetime_sold, "lifetime_earned": lifetime_earned,
		"color": [color.r, color.g, color.b],
	}


static func from_dict(d: Dictionary) -> Employee:
	var e := Employee.new()
	e.id = String(d.get("id", ""))
	e.name = String(d.get("name", "Worker"))
	e.archetype = String(d.get("archetype", "hand"))
	e.property_id = String(d.get("property_id", ""))
	e.assignment = String(d.get("assignment", ASSIGN_IDLE))
	e.wage = int(d.get("wage", 45))
	e.skill = float(d.get("skill", 0.35))
	e.loyalty = float(d.get("loyalty", 0.5))
	e.discretion = float(d.get("discretion", 0.4))
	e.days_employed = int(d.get("days_employed", 0))
	e.unpaid_days = int(d.get("unpaid_days", 0))
	e.lifetime_produced = int(d.get("lifetime_produced", 0))
	e.lifetime_sold = int(d.get("lifetime_sold", 0))
	e.lifetime_earned = int(d.get("lifetime_earned", 0))
	var c: Array = d.get("color", [0.6, 0.7, 0.8])
	if c.size() >= 3:
		e.color = Color(c[0], c[1], c[2])
	return e
