#!/usr/bin/env node
/**
 * One-time build step: vendors the open-licence webfonts into assets/fonts so the
 * game renders identically offline. Re-run only when changing the type stack.
 *   Archivo Black - OFL   Bebas Neue - OFL   Inter - OFL   JetBrains Mono - OFL
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'assets/fonts');
mkdirSync(OUT, { recursive: true });

const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';
const FAMILIES = [
  { file: 'archivo-black-400', query: 'Archivo+Black', family: 'Archivo Black', weight: 400 },
  { file: 'bebas-neue-400', query: 'Bebas+Neue', family: 'Bebas Neue', weight: 400 },
  { file: 'inter-400', query: 'Inter:wght@400', family: 'Inter', weight: 400 },
  { file: 'inter-500', query: 'Inter:wght@500', family: 'Inter', weight: 500 },
  { file: 'inter-600', query: 'Inter:wght@600', family: 'Inter', weight: 600 },
  { file: 'inter-800', query: 'Inter:wght@800', family: 'Inter', weight: 800 },
  { file: 'jetbrains-mono-500', query: 'JetBrains+Mono:wght@500', family: 'JetBrains Mono', weight: 500 },
];

const faces = [];
for (const f of FAMILIES) {
  const css = await (await fetch(`https://fonts.googleapis.com/css2?family=${f.query}&display=swap`, { headers: { 'user-agent': UA } })).text();
  const blocks = css.split('/*').map((b) => `/*${b}`);
  const latin = blocks.find((b) => b.startsWith('/* latin */')) || blocks.at(-1);
  const url = /https:\/\/fonts\.gstatic\.com[^)]*\.woff2/.exec(latin)?.[0];
  if (!url) throw new Error(`no woff2 for ${f.query}`);
  const buf = Buffer.from(await (await fetch(url, { headers: { 'user-agent': UA } })).arrayBuffer());
  writeFileSync(join(OUT, `${f.file}.woff2`), buf);
  faces.push({ ...f, bytes: buf.length });
  console.log(`${f.file}.woff2  ${(buf.length / 1024).toFixed(1)} KB`);
}

const css = `/* Vendored open-licence type. Generated by tools/fetch-fonts.mjs - do not edit. */
${faces.map((f) => `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url('./${f.file}.woff2') format('woff2');
}`).join('\n')}
`;
writeFileSync(join(OUT, 'fonts.css'), css, 'utf8');
console.log('assets/fonts/fonts.css written');
