class_name VehicleDB
extends RefCounted
## Drivable vehicles sold by Teo Marchetti.
##
## Handling values feed the arcade controller in src/vehicles/vehicle.gd.
## "heat_shield" reduces the suspicion generated by contraband in the boot.

static func data() -> Dictionary:
	return {
		"wasp_90": {
			"name": "Wasp 90",
			"desc": "A scooter with a milk crate zip-tied to the back. Parks anywhere.",
			"price": 2300, "top_speed": 13.5, "accel": 9.0, "grip": 5.5, "brake": 12.0,
			"storage": 12, "heat_shield": 0.05, "body": Vector3(0.8, 0.9, 1.9),
			"color": Color(0.85, 0.75, 0.25), "seats": 1, "unlock_level": 2,
		},
		"kestrel_van": {
			"name": "Kestrel 40 Van",
			"desc": "White panel van, no windows in the back. The single most useful object in Cobalt Bay.",
			"price": 8900, "top_speed": 16.0, "accel": 6.5, "grip": 4.6, "brake": 11.0,
			"storage": 70, "heat_shield": 0.35, "body": Vector3(2.0, 2.2, 5.0),
			"color": Color(0.86, 0.87, 0.88), "seats": 2, "unlock_level": 4,
		},
		"tidewater_pickup": {
			"name": "Tidewater Pickup",
			"desc": "Rusted flatbed with a working winch. Handles gravel and gates equally.",
			"price": 16500, "top_speed": 18.5, "accel": 7.5, "grip": 5.2, "brake": 12.5,
			"storage": 45, "heat_shield": 0.15, "body": Vector3(2.0, 1.9, 5.2),
			"color": Color(0.35, 0.45, 0.4), "seats": 2, "unlock_level": 6,
		},
		"meridian_courier": {
			"name": "Meridian Courier",
			"desc": "A bonded-freight estate with genuine Bureau decals. Patrols wave it through.",
			"price": 34000, "top_speed": 21.0, "accel": 8.5, "grip": 6.2, "brake": 14.0,
			"storage": 55, "heat_shield": 0.6, "body": Vector3(1.9, 1.6, 4.8),
			"color": Color(0.3, 0.4, 0.6), "seats": 4, "unlock_level": 10,
		},
		"sable_gt": {
			"name": "Sable GT",
			"desc": "Fast, black, and completely inappropriate for a delivery. You will buy it anyway.",
			"price": 98000, "top_speed": 30.0, "accel": 13.0, "grip": 7.8, "brake": 17.0,
			"storage": 18, "heat_shield": 0.0, "body": Vector3(1.9, 1.25, 4.5),
			"color": Color(0.09, 0.09, 0.11), "seats": 2, "unlock_level": 16,
		},
	}


static func ids() -> PackedStringArray:
	return PackedStringArray(["wasp_90", "kestrel_van", "tidewater_pickup",
		"meridian_courier", "sable_gt"])
